Torskyi currency
OrestTorskyi/TAQC_Team_5_Project pull request #1
Opened 2021-04-23 10:28 UTC by OrestTorskyi

There was done the next list of tests cases:
1. Test for adding new currency:
a) by checking success message
b) by comparing the number of elements before and after adding
2. Test for deleting currency:
a) by checking success message
b) by comparing the number of elements before and after deleting
3. Test for editing currency value:
a) by checking success message
b) by comparing values of currency before and after editing
3. Test for editing currency status:
a) by checking success message
4. Test for checking possibility of selecting currency:
a) when currency status is enabled
b) when currency status is disabled

2021-04-30 10:57 UTC, adomanich requested changes

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/pages/AdminNavigation.java
> +    @FindBy(xpath = ".//ul[@id = 'collapse7']//a[contains(@href,'#collapse7-2')]")
I believe it is better to update this locator, looks like that id is autogenerated, you can search by text here

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/CurrencyPageBL.java
> +    public AddNewCurrencyPageBL getToAddingNewCurrency() {
Please, rename it to clickAddNewCurrencyButton()

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/CurrencyPageBL.java
> +    public EditCurrencyPageBL getToEditCurrencyPage() {
Please, rename it to clickEditCurrencyButton()

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/CurrencyPageBL.java
> +    }
Maybe it is better to remove currency by title? - it will make your method more flexible

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/CurrencyPageBL.java
> +        Assert.assertNotEquals(initialValue, resultValue);
Please, add error message

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +        Assert.assertFalse(currencyInList(currencyTitle));
Please, add an error message

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +        return this;
It is better to make all "verify" methods with void return type

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +    private boolean currencyInList(String currencyTitle) {
Please, rename it to isCurrencyInList()

2021-04-30 10:57 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +            } else isInList = false;
Please, replace it on:
else {
inList = false;
}

2021-04-30 10:57 UTC, adomanich commented on src/test/java/AddNewCurrencyTestByMessage.java
> +}
Please, put two tests related to currency adding into one test class

2021-04-30 10:57 UTC, adomanich commented on src/test/java/CheckCurrencyIsEnabledInShopTest.java
> +}
Please, put two tests related to currency enabling/disabling into one test class

2021-04-30 10:57 UTC, adomanich commented on src/test/java/DeleteCurrencyTestByMessage.java
> +}
Please, put two tests related to currency removing into one test class

2021-04-30 10:57 UTC, adomanich commented on src/test/java/EditCurrencyValueTestByMessage.java
> +}
Please, put three tests related to currency editing into one test class

2021-05-09 19:50 UTC, adomanich approved these changes

2021-05-13 10:59 UTC, Viktoria18 approved these changes

2021-05-13 15:07 UTC, merged